[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "22"

# Form handling
[forms]
  # Enable form detection
  
# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects (moved from astro.config.mjs to be more explicit)
[[redirects]]
  from = "/feed.xml"
  to = "/rss.xml"
  status = 302